def test_import():
    import nr_metadata.version  # noqa
    import nr_metadata.ui_schema.identifiers  # noqa
    import nr_metadata.ui_schema.subjects  # noqa
    import nr_metadata.schema.identifiers  # noqa
    import nr_metadata.common.records.models  # noqa
    import nr_metadata.common.records.api  # noqa
    import nr_metadata.common.records.dumpers.dumper  # noqa
    import nr_metadata.common.records.dumpers.edtf  # noqa
    import nr_metadata.common.records.dumpers.multilingual  # noqa
    import nr_metadata.common.config  # noqa
    import nr_metadata.common.version  # noqa
    import nr_metadata.common.resources.records.config  # noqa
    import nr_metadata.common.resources.records.ui  # noqa
    import nr_metadata.common.resources.records.resource  # noqa
    import nr_metadata.common.proxies  # noqa
    import nr_metadata.common.views.records.api  # noqa
    import nr_metadata.common.views.records.app  # noqa
    import nr_metadata.common.services.records.service  # noqa
    import nr_metadata.common.services.records.ui_schema_common  # noqa
    import nr_metadata.common.services.records.config  # noqa
    import nr_metadata.common.services.records.ui_schema_datatypes  # noqa
    import nr_metadata.common.services.records.schema_datatypes  # noqa
    import nr_metadata.common.services.records.permissions  # noqa
    import nr_metadata.common.services.records.search  # noqa
    import nr_metadata.common.services.records.schema_common  # noqa
    import nr_metadata.common.services.records.facets  # noqa
    import nr_metadata.common.ext  # noqa
    import nr_metadata.documents.records.models  # noqa
    import nr_metadata.documents.records.api  # noqa
    import nr_metadata.documents.records.dumpers.dumper  # noqa
    import nr_metadata.documents.records.dumpers.edtf  # noqa
    import nr_metadata.documents.records.dumpers.multilingual  # noqa
    import nr_metadata.documents.config  # noqa
    import nr_metadata.documents.version  # noqa
    import nr_metadata.documents.resources.records.config  # noqa
    import nr_metadata.documents.resources.records.ui  # noqa
    import nr_metadata.documents.resources.records.resource  # noqa
    import nr_metadata.documents.proxies  # noqa
    import nr_metadata.documents.views.records.api  # noqa
    import nr_metadata.documents.views.records.app  # noqa
    import nr_metadata.documents.services.records.ui_schema  # noqa
    import nr_metadata.documents.services.records.service  # noqa
    import nr_metadata.documents.services.records.config  # noqa
    import nr_metadata.documents.services.records.permissions  # noqa
    import nr_metadata.documents.services.records.search  # noqa
    import nr_metadata.documents.services.records.facets  # noqa
    import nr_metadata.documents.services.records.schema  # noqa
    import nr_metadata.documents.ext  # noqa
