name: Build, test and publish

on: push

permissions:
  id-token: write
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      oarepo: 12

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Use built nr-metadata artifacts
        uses: actions/download-artifact@v3
        with:
          name: nr_metadata_dist
          path: nr_metadata_dist
      - name: Use built omb-nr artifacts
        uses: actions/download-artifact@v3
        with:
          name: omb_nr_dist
          path: omb_nr_dist

      - name: Publish nr-metadata package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip_existing: true
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
          packages-dir: nr_metadata_dist

      - name: Publish omb-nr package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip_existing: true
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
          packages-dir: omb_nr_dist
